// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtoerqgjwwubqfkkjhif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0b2VycWdqd3d1YnFma2tqaGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODUwNjUsImV4cCI6MjA2NDI2MTA2NX0.gzQPbvooCUi5Bt4Qr33nTGfCGHStciAwvlQuuRdusvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);